title: foo bah baz!
# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
collections:
  sub_pages:
    output: true
    permalink: /:name
    defaults:
    - scope:
        path: ""
      values:
        layout: default

